import { env } from "../env.js";
import type { EmailDetail, EmailReplyDraft, MeetingPrep } from "../types.js";

interface MeetingPrepInput {
  title: string;
  startTime: string;
  endTime: string;
  timeZone: string | null;
  description: string;
  organizer?: string | null;
  attendees?: string[];
  userNotes?: string | null;
}

function unique(values: string[]) {
  return [...new Set(values.map((value) => value.trim()).filter(Boolean))];
}

function normalizeWhitespace(value: string) {
  return value.replace(/\r/g, "").replace(/[ \t]+/g, " ").replace(/\n{3,}/g, "\n\n").trim();
}

function sanitizeRichText(value: string) {
  return normalizeWhitespace(
    value
      .replace(/<!--[\s\S]*?-->/g, "")
      .replace(/<head[\s\S]*?<\/head>/gi, "")
      .replace(/<style[\s\S]*?<\/style>/gi, "")
      .replace(/<script[\s\S]*?<\/script>/gi, "")
      .replace(/<meta[^>]*>/gi, "")
      .replace(/<[^>]+>/g, "\n")
      .replace(/&nbsp;/gi, " ")
      .replace(/&amp;/gi, "&")
      .replace(/&lt;/gi, "<")
      .replace(/&gt;/gi, ">")
  );
}

function clip(value: string, max = 2800) {
  if (value.length <= max) return value;
  return `${value.slice(0, max).trim()}\n…`;
}

function splitSentences(value: string) {
  return normalizeWhitespace(value)
    .split(/(?<=[.!?])\s+/)
    .map((entry) => entry.trim())
    .filter(Boolean);
}

function extractEmailAddress(value: string | null | undefined) {
  if (!value) return null;
  const match = value.match(/<([^>]+)>/);
  const raw = (match?.[1] ?? value).trim();
  const cleaned = raw.replace(/^mailto:/i, "").trim();
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(cleaned) ? cleaned : null;
}

function displayNameFromAddress(value: string | null | undefined) {
  if (!value) return "there";
  const match = value.match(/^(.+?)\s*</);
  const direct = match?.[1]?.trim() || value.split("@")[0]?.trim() || "there";
  return direct.replace(/^['"]|['"]$/g, "");
}

function isBotLikeAddress(value: string | null | undefined) {
  if (!value) return false;
  return /(noreply|notification|bitbucket|service-now|automated|mailer-daemon|do-not-reply)/i.test(value);
}

function stripNotificationNoiseLines(text: string) {
  return text
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .filter(
      (line) =>
        !/(view pull request|view in orca|notification settings|you can unwatch|stop receiving email updates|priority ✅|priority passed|merged the pull request|approval .* merged|comment added by|reply to this email|privacy statement|manage notifications|this message was sent|generated by|unsubscribe)/i.test(
          line
        )
    )
    .filter((line) => !/^\d{1,2}:\d{2}(?::\d{2})?\s*(am|pm)?$/i.test(line))
    .join("\n");
}

function cleanWorkText(value: string) {
  return stripNotificationNoiseLines(sanitizeRichText(value)).replace(/\n{3,}/g, "\n\n").trim();
}

function extractActionSignals(text: string) {
  const normalized = cleanWorkText(text);
  const sentences = splitSentences(normalized);
  const strongSignals = sentences.filter((sentence) =>
    /(action required|please|can you|could you|need you|reply|review|approve|follow up|confirm|check|fix|update|complete|comment|mentioned you|requested review|requested changes|deadline|due)/i.test(
      sentence
    )
  );
  const dueSignals = sentences.filter((sentence) => /(today|tomorrow|by\s+\w+|deadline|ending|expire|due)/i.test(sentence));
  const nounSignals = sentences.filter((sentence) =>
    /(password|pull request|pr\b|jira|ticket|bucket|lifecycle|migration|account|review|comment|bug|issue|release|access)/i.test(
      sentence
    )
  );

  return unique([...strongSignals.slice(0, 3), ...dueSignals.slice(0, 2), ...nounSignals.slice(0, 2)]).slice(0, 5);
}

function buildThreadSummary(detail: EmailDetail) {
  const latest = clip(cleanWorkText(detail.body ?? ""), 1400);
  const thread = detail.thread
    .slice(-3)
    .map((message) => {
      const sender = message.from ?? "Unknown sender";
      const subject = message.subject ?? "No subject";
      const body = clip(cleanWorkText(message.body ?? ""), 500);
      return `From: ${sender}\nSubject: ${subject}\n${body}`;
    })
    .join("\n\n---\n\n");

  return {
    latest,
    thread
  };
}

function chooseHeuristicReplyLine(detail: EmailDetail, actionSignals: string[]) {
  const text = cleanWorkText(`${detail.subject ?? ""}\n${detail.body ?? ""}`).toLowerCase();
  if (/password.*expire/.test(text)) {
    return "Thanks for the reminder. I saw the password expiry notice and will take care of it before the deadline.";
  }
  if (/\bpull request\b|\bpr\b|requested review|requested changes|review/.test(text)) {
    return "I saw the pull request update and will review it and follow up on any feedback or next actions shortly.";
  }
  if (/comment|mentioned you/.test(text)) {
    return "I saw the update and will review the linked thread and follow up on the relevant next step.";
  }
  if (/action required|urgent|missing|lifecycle|bucket|access/.test(text)) {
    return "I reviewed the request and will follow up on the required action shortly.";
  }
  if (actionSignals[0]) {
    return "I reviewed this and will follow up with the next step shortly.";
  }
  return "I reviewed this and will follow up shortly with the next step.";
}

function heuristicEmailReply(detail: EmailDetail, userIntent?: string | null): EmailReplyDraft {
  const senderEmail = isBotLikeAddress(detail.from) ? null : extractEmailAddress(detail.from);
  const senderName = displayNameFromAddress(detail.from);
  const cleanedContext = cleanWorkText(
    `${detail.subject ?? ""}\n${detail.body ?? ""}\n${detail.thread.map((message) => message.body).join("\n")}`
  );
  const actionSignals = extractActionSignals(cleanedContext);
  const summary = actionSignals[0] ?? detail.subject?.trim() ?? "Follow up on the latest message";
  const responseLine = userIntent?.trim() || chooseHeuristicReplyLine(detail, actionSignals);
  const body = [
    senderEmail ? `Hi ${senderName},` : "Hi,",
    "",
    responseLine,
    userIntent?.trim() ? null : "I’ll share a more concrete update once I finish the review.",
    "",
    "Best,",
    "[Your Name]"
  ]
    .filter(Boolean)
    .join("\n");

  return {
    subject: detail.subject?.startsWith("Re:") ? detail.subject : `Re: ${detail.subject ?? "Follow-up"}`,
    to: senderEmail ? [senderEmail] : [],
    cc: [],
    body,
    summary,
    actionItems: actionSignals,
    rationale: "Built from the cleaned email content, prior thread, and the concrete work signals detected in the message without copying notification boilerplate."
  };
}

function extractMeetingBullets(description: string) {
  const normalized = cleanWorkText(description);
  const explicitBullets = normalized
    .split(/\n+/)
    .map((line) => line.replace(/^[\-\*\u2022]\s*/, "").trim())
    .filter((line) => line.length > 10);

  if (explicitBullets.length) {
    return explicitBullets.slice(0, 8);
  }

  return splitSentences(normalized).slice(0, 8);
}

function buildMeetingNotes(prep: Omit<MeetingPrep, "notes">) {
  const sections: string[] = [
    prep.title,
    "",
    `Summary: ${prep.summary}`,
    "",
    "Objectives",
    ...(prep.objectives.length ? prep.objectives.map((item) => `- ${item}`) : ["- No clear objective could be inferred from the invite."]),
    "",
    "Preparation checklist",
    ...(prep.checklist.length ? prep.checklist.map((item) => `- ${item}`) : ["- Review the invite and current work context before joining."]),
    "",
    "Talking points",
    ...(prep.talkingPoints.length ? prep.talkingPoints.map((item) => `- ${item}`) : ["- Be ready with a concise status update."]),
    "",
    "Questions to ask",
    ...(prep.questions.length ? prep.questions.map((item) => `- ${item}`) : ["- Clarify the expected decision or output if it is still unclear."]),
    "",
    "Risks / watchouts",
    ...(prep.risks.length ? prep.risks.map((item) => `- ${item}`) : ["- Watch for missing owners, unclear scope, or decisions without follow-up."]),
    "",
    `Rationale: ${prep.rationale}`
  ];

  return sections.join("\n");
}

function heuristicMeetingPrep(input: MeetingPrepInput): MeetingPrep {
  const cleanedDescription = cleanWorkText(input.description);
  const bullets = extractMeetingBullets(cleanedDescription);
  const objectives = unique([
    bullets[0] ?? "",
    /standup|sync|daily/i.test(input.title) ? "Give a concise update on current work, blockers, and next steps." : "",
    /review|demo|showcase/i.test(input.title) ? "Review progress, gather feedback, and align on follow-up actions." : ""
  ]).filter(Boolean).slice(0, 3);

  const checklist = unique([
    bullets[0] ? `Review the invite context related to "${bullets[0].slice(0, 80)}".` : "",
    input.userNotes?.trim() ? `Prepare for: ${input.userNotes.trim()}` : "",
    input.organizer ? `Be clear on what ${input.organizer} likely expects from this meeting.` : "",
    input.attendees?.length ? "Know who the key attendees are and what decisions may depend on them." : ""
  ]).slice(0, 4);

  const talkingPoints = unique([
    bullets[0] ?? "",
    bullets[1] ?? "",
    "Current status, blockers, and the recommended next step."
  ]).filter(Boolean).slice(0, 4);

  const questions = unique([
    "What decision or output is expected by the end of the meeting?",
    bullets[2] ? `Do we have alignment on "${bullets[2].slice(0, 70)}"?` : "",
    /sync|standup/i.test(input.title) ? "Are there any blockers or dependencies that need escalation?" : ""
  ]).filter(Boolean).slice(0, 4);

  const risks = unique([
    bullets.length === 0 ? "The invite has very little detail, so confirm scope quickly." : "",
    input.attendees?.length && input.attendees.length > 8 ? "Large attendee list may mean broad discussion and slower decisions." : "",
    /hackathon|showcase|office hours|optional/i.test(input.title) ? "Clarify whether attendance is informational or action-oriented." : ""
  ]).filter(Boolean).slice(0, 3);

  const draft: Omit<MeetingPrep, "notes"> = {
    title: input.title,
    summary:
      bullets[0] ??
      input.userNotes?.trim() ??
      (/standup|sync|daily/i.test(input.title)
        ? "Be ready with a concise status update, blockers, and the next step."
        : "Clarify the goal of the meeting quickly and leave with clear owners and next steps."),
    objectives,
    checklist,
    talkingPoints,
    questions,
    risks,
    rationale: "Prepared from the cleaned meeting description, title, attendees, organizer, and your optional guidance."
  };

  return {
    ...draft,
    notes: buildMeetingNotes(draft)
  };
}

async function callOpenAIJson<T>(input: unknown, schema: object, name: string, systemPrompt: string): Promise<T | null> {
  if (!env.openAiApiKey) {
    return null;
  }

  try {
    const response = await fetch(`${env.openAiApiBaseUrl}/v1/responses`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${env.openAiApiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: env.openAiModel,
        input: [
          {
            role: "system",
            content: [{ type: "input_text", text: systemPrompt }]
          },
          {
            role: "user",
            content: [{ type: "input_text", text: JSON.stringify(input) }]
          }
        ],
        text: {
          format: {
            type: "json_schema",
            name,
            schema
          }
        }
      })
    });

    if (!response.ok) return null;
    const json = (await response.json()) as { output_text?: string };
    if (!json.output_text) return null;
    return JSON.parse(json.output_text) as T;
  } catch {
    return null;
  }
}

function normalizeRecipients(values: string[]) {
  return unique(
    values
      .map((value) => extractEmailAddress(value) ?? value.trim())
      .filter((value) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))
  );
}

export async function generateEmailReplyDraft(detail: EmailDetail, userIntent?: string | null): Promise<EmailReplyDraft> {
  const fallback = heuristicEmailReply(detail, userIntent);
  const threadSummary = buildThreadSummary(detail);
  const aiDraft = await callOpenAIJson<EmailReplyDraft>(
    {
      latestMessage: {
        subject: detail.subject,
        fromDisplay: detail.from,
        fromEmail: extractEmailAddress(detail.from),
        receivedAt: detail.receivedAt,
        body: threadSummary.latest
      },
      previousThread: threadSummary.thread,
      detectedActionSignals: fallback.actionItems,
      userIntent: userIntent ?? null
    },
    {
      type: "object",
      additionalProperties: false,
      required: ["subject", "to", "cc", "body", "summary", "actionItems", "rationale"],
      properties: {
        subject: { type: "string" },
        to: { type: "array", items: { type: "string" } },
        cc: { type: "array", items: { type: "string" } },
        body: { type: "string" },
        summary: { type: "string" },
        actionItems: { type: "array", items: { type: "string" } },
        rationale: { type: "string" }
      }
    },
    "email_reply_draft",
    [
      "Draft a practical work email reply from the actual message and prior thread.",
      "Be concrete, concise, and useful. Do not invent facts, deadlines, or commitments that were not stated.",
      "Do not quote, paste, or paraphrase large parts of the sender's message back to them.",
      "Do not echo notification boilerplate, logs, timestamps, approval metadata, or footer content.",
      "If the user's guidance is vague or missing, write a safe but helpful acknowledgement with the next reasonable step.",
      "If the sender looks like a bot or notification system, it is acceptable to leave to/cc empty instead of replying to the sender.",
      "Use plain recipient email addresses only in to/cc.",
      "The body should be immediately editable and ready to send."
    ].join(" ")
  );

  return {
    subject: aiDraft?.subject?.trim() || fallback.subject,
    to: normalizeRecipients(aiDraft?.to?.length ? aiDraft.to : fallback.to),
    cc: normalizeRecipients(aiDraft?.cc?.length ? aiDraft.cc : fallback.cc),
    body: normalizeWhitespace(aiDraft?.body?.trim() || fallback.body),
    summary: aiDraft?.summary?.trim() || fallback.summary,
    actionItems: unique((aiDraft?.actionItems?.length ? aiDraft.actionItems : fallback.actionItems).map((item) => item.trim())).slice(0, 5),
    rationale: aiDraft?.rationale?.trim() || fallback.rationale
  };
}

export async function generateMeetingPrep(input: MeetingPrepInput): Promise<MeetingPrep> {
  const fallback = heuristicMeetingPrep(input);
  const aiPrep = await callOpenAIJson<MeetingPrep>(
    {
      title: input.title,
      startTime: input.startTime,
      endTime: input.endTime,
      timeZone: input.timeZone,
      organizer: input.organizer ?? null,
      attendees: input.attendees ?? [],
      description: clip(cleanWorkText(input.description || ""), 2400),
      extractedInviteBullets: extractMeetingBullets(input.description).slice(0, 6),
      userNotes: input.userNotes ?? null
    },
    {
      type: "object",
      additionalProperties: false,
      required: ["title", "summary", "objectives", "checklist", "talkingPoints", "questions", "risks", "rationale"],
      properties: {
        title: { type: "string" },
        summary: { type: "string" },
        objectives: { type: "array", items: { type: "string" } },
        checklist: { type: "array", items: { type: "string" } },
        talkingPoints: { type: "array", items: { type: "string" } },
        questions: { type: "array", items: { type: "string" } },
        risks: { type: "array", items: { type: "string" } },
        rationale: { type: "string" }
      }
    },
    "meeting_prep",
    [
      "Create a practical meeting preparation brief using the actual invite content.",
      "Focus on likely goal, what the user should review beforehand, what they should say, what to ask, and what could go wrong.",
      "Ignore HTML fragments, formatting artifacts, metadata lines, and email-wrapper noise.",
      "Avoid generic filler. If the invite is vague, say that clearly and provide only minimal safe prep.",
      "Keep each list item specific and actionable."
    ].join(" ")
  );

  const prepared: Omit<MeetingPrep, "notes"> = {
    title: aiPrep?.title?.trim() || fallback.title,
    summary: aiPrep?.summary?.trim() || fallback.summary,
    objectives: unique(aiPrep?.objectives ?? fallback.objectives).slice(0, 5),
    checklist: unique(aiPrep?.checklist ?? fallback.checklist).slice(0, 6),
    talkingPoints: unique(aiPrep?.talkingPoints ?? fallback.talkingPoints).slice(0, 6),
    questions: unique(aiPrep?.questions ?? fallback.questions).slice(0, 5),
    risks: unique(aiPrep?.risks ?? fallback.risks).slice(0, 5),
    rationale: aiPrep?.rationale?.trim() || fallback.rationale
  };

  return {
    ...prepared,
    notes: buildMeetingNotes(prepared)
  };
}
