export type TaskSource = "Email" | "Jira" | "Manual";
export type TaskPriority = "High" | "Medium" | "Low";
export type TaskStatus = "Not Started" | "In Progress" | "Completed";
export type TaskEffortBucket = "15 min" | "30 min" | "1 hour" | "2+ hours";
export type ReminderStatus = "active" | "dismissed" | "resolved";
export type ReminderKind = "email_follow_up" | "jira_stale" | "deferred_due" | "meeting_prep";
export type WorkloadState = "Underloaded" | "Balanced" | "Overloaded";

export interface Task {
  id: number;
  title: string;
  source: TaskSource;
  priority: TaskPriority;
  status: TaskStatus;
  sourceLink: string | null;
  sourceRef: string | null;
  sourceThreadRef: string | null;
  jiraStatus: string | null;
  ignored: number;
  deferredUntil: string | null;
  reminderState: ReminderStatus | null;
  lastRemindedAt: string | null;
  estimatedEffortBucket: TaskEffortBucket | null;
  priorityScore: number | null;
  priorityExplanation: string | null;
  taskAgeDays: number;
  carryForwardCount: number;
  completedAt: string | null;
  lastActivityAt: string | null;
  manualOverrideFlags: string[];
  createdAt: string;
  updatedAt: string;
}

export interface Meeting {
  id: number;
  externalId: string | null;
  title: string;
  startTime: string;
  endTime: string;
  timeZone: string | null;
  durationMinutes: number;
  meetingLink: string | null;
  meetingLinkType: "join" | "calendar" | null;
  isCancelled: boolean;
  createdAt: string;
}

export interface IntegrationConnection {
  provider: "microsoft" | "jira";
  status: "connected" | "disconnected" | "error";
  accountLabel: string | null;
  configJson: string | null;
  accessToken: string | null;
  refreshToken: string | null;
  expiresAt: string | null;
  errorMessage: string | null;
  updatedAt: string;
}

export interface Reminder {
  id: number;
  reminderKey: string;
  taskId: number | null;
  kind: ReminderKind;
  title: string;
  reason: string;
  status: ReminderStatus;
  sourceLink: string | null;
  sourceLabel: string | null;
  scheduledFor: string | null;
  createdAt: string;
  updatedAt: string;
  dismissedAt: string | null;
  throttleUntil: string | null;
}

export interface AutomationSettings {
  scheduleEnabled: boolean;
  scheduleTimeLocal: string;
  scheduleTimezone: string;
  remindersEnabled: boolean;
  reminderCadenceHours: number;
  desktopNotificationsEnabled: boolean;
  lastAutoGeneratedAt: string | null;
  schedulerLastRunAt: string | null;
  schedulerLastStatus: "idle" | "ok" | "error";
  schedulerLastError: string | null;
}

export interface WorkloadSummary {
  totalMeetingMinutes: number;
  totalTaskMinutes: number;
  totalPlannedMinutes: number;
  state: WorkloadState;
}

export interface TodayPayload {
  meetings: Meeting[];
  tasks: Record<TaskPriority, Task[]>;
  reminders: Reminder[];
  workload: WorkloadSummary;
  deferredTaskCount: number;
  automation: AutomationSettings;
  sync: {
    microsoft: string | null;
    jira: string | null;
    lastGeneratedAt: string | null;
  };
  warnings: string[];
}

export interface JiraDetail {
  type: "jira";
  key: string;
  title: string;
  status: string | null;
  priority: string | null;
  description: string | null;
  storyPoints: number | null;
  assignee: string | null;
  reporter: string | null;
  labels: string[];
  subtasks: Array<{
    key: string;
    title: string;
    status: string | null;
  }>;
  comments: Array<{
    author: string;
    createdAt: string | null;
    body: string;
  }>;
  worklogs: Array<{
    author: string;
    startedAt: string | null;
    timeSpent: string | null;
    comment: string | null;
  }>;
}

export interface EmailThreadMessage {
  id: string;
  from: string | null;
  to: string[];
  cc: string[];
  subject: string | null;
  receivedAt: string | null;
  body: string;
}

export interface EmailDetail {
  type: "email";
  from: string | null;
  to: string[];
  cc: string[];
  subject: string | null;
  receivedAt: string | null;
  body: string;
  thread: EmailThreadMessage[];
}

export type TaskDetail = JiraDetail | EmailDetail;
